USE CRYSTN_EXPTS;

# stored function:
# what is the success rate of reactions for a specified molecule?
DELIMITER $$

CREATE FUNCTION MOLECULE_COXTAL_RATE(m_name VARCHAR(50))
RETURNS FLOAT
DETERMINISTIC
BEGIN
	DECLARE SUCCESS_RATE FLOAT DEFAULT 0;
	SELECT AVG(exp.SUCCESS)
    INTO SUCCESS_RATE
    FROM EXPERIMENTS exp
    WHERE (exp.CF1_MOL_ID =
			(SELECT m.MOL_ID
			FROM MOLECULES m
			WHERE
			m.MOL_NAME = m_name))
			OR (exp.CF2_MOL_ID = 
			(SELECT m.MOL_ID
			FROM MOLECULES m
			WHERE
			m.MOL_NAME = m_name));
	RETURN SUCCESS_RATE;
END$$

DELIMITER ;

# Query for given compund
SET @COFORMER_NAME := '1,3-diiodobenzene';
SELECT @COFORMER_NAME, MOLECULE_COXTAL_RATE(@COFORMER_NAME) as Cocrystallisation_Rate;
    
#DROP FUNCTION MOLECULE_COXTAL_RATE;

# function to get molecule's ID from its name
DELIMITER $$
CREATE FUNCTION GET_MOL_ID_FROM_NAME(m_name VARCHAR(50))
RETURNS INT
DETERMINISTIC
BEGIN
	DECLARE molecule_ID INT;
    SELECT MOL_ID INTO molecule_ID
    FROM MOLECULES
    WHERE
    LOWER(MOL_NAME) = LOWER(m_name);
    RETURN molecule_ID;
END$$
DELIMITER ;

#SELECT GET_MOL_ID_FROM_NAME('Ethanol');

# function to get researcher's ID from name
DELIMITER $$
CREATE FUNCTION GET_RESEARCHER_ID_FROM_NAME
(first_name VARCHAR(50), 
last_name VARCHAR(50))
RETURNS INT
DETERMINISTIC
BEGIN
	DECLARE res_ID INT;
    SELECT RESEARCHER_ID INTO RES_ID
    FROM RESEARCHERS
    WHERE
    (LOWER(R_FIRSTNAME) = LOWER(first_name)) 
    AND (LOWER(R_SECONDNAME) = LOWER(last_name));
    RETURN RES_ID;
END$$
DELIMITER ;

#SELECT GET_RESEARCHER_ID_FROM_NAME("Naomi", "Ohara");

# function to get molecule's ID from its name
DELIMITER $$
CREATE FUNCTION GET_PXRD_ID_FROM_FILENAME(file_name VARCHAR(50))
RETURNS INT
DETERMINISTIC
BEGIN
	DECLARE PXRDID INT;
    SELECT PXRD_ID INTO PXRDID
    FROM PXRD_EXPTS
    WHERE
    LOWER(FILENAME) = LOWER(file_name);
    RETURN PXRDID;
END$$
DELIMITER ;

#SELECT GET_PXRD_ID_FROM_FILENAME("IN PROGRESS");