USE CRYSTN_EXPTS;

# VIEW - See pxrd info for each experiment

CREATE OR REPLACE VIEW VW_pxrd_info
AS
SELECT
e.EXPT_ID, p.FILENAME, i.I_NAME, i.RADIATION
FROM EXPERIMENTS e
JOIN
PXRD_EXPTS p
ON e.PXRD_ID = p.PXRD_ID
INNER JOIN PXRD_INSTRUMENTS i
ON p.INSTRUMENT_ID = i.INSTRUMENT_ID;


#DROP VIEW VW_PXRD_INFO;

# see all chemicals used in each experiment
CREATE OR REPLACE VIEW VW_expt_with_chemicals
AS
SELECT
e.EXPT_ID,
m1.MOL_NAME as CF1_name,
m2.MOL_NAME as CF2_name,
m3.MOL_NAME as solv_name
FROM EXPERIMENTS e
JOIN MOLECULES m1
ON e.CF1_MOL_ID = m1.MOL_ID
JOIN MOLECULES m2
ON e.CF2_MOL_ID = m2.MOL_ID
JOIN MOLECULES m3
ON e.SOLVENT_MOL_ID = m3.MOL_ID; 


